# Generated by Django 2.0.7 on 2018-07-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('adress', models.TextField()),
                ('tel', models.DecimalField(decimal_places=0, max_digits=15)),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anaboliki.Cities')),
            ],
        ),
    ]
