# Generated by Django 2.0.7 on 2018-07-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('anaboliki', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
    ]
