# Generated by Django 2.0.7 on 2018-07-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anaboliki', '0002_auto_20180721_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='activity_name',
            new_name='name',
        ),
    ]
